/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ehealth.forms;

import com.ehealth.dao.EquipmentTypeDAO;
import com.ehealth.dao.Impl.EquipmentTypeDAOImpl;
import com.ehealth.dao.Impl.UserPermissionDAOImpl;
import com.ehealth.dao.UserPermissionDAO;
import com.ehealth.models.EquipmentTypeModel;
import com.ehealth.models.UserPermissionModel;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Akash
 */
public class EquipmentTypeFrame extends javax.swing.JFrame {

    private Integer equipmentTypeId;

    /**
     * Creates new form EquipmentTypeFrame
     */
    public EquipmentTypeFrame() {
        initComponents();
        setIcon();
        populateMyTable();
        btnAdd.setVisible(false);
        btnDelete.setVisible(false);
        btnUpdate.setVisible(false);
        checkPermissions();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        equipmentLabel = new javax.swing.JLabel();
        equipmentTypeBar = new javax.swing.JSeparator();
        txtEquipmentType = new javax.swing.JTextField();
        lbEquipmentType = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        tablePanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        equipmentTypeTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Equipment Type");
        setResizable(false);

        backgroundPanel.setBackground(new java.awt.Color(29, 29, 29));
        backgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        equipmentLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        equipmentLabel.setForeground(new java.awt.Color(255, 255, 255));
        equipmentLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ehealth/images/icons8_Vacuum_Cleaner_32px.png"))); // NOI18N
        equipmentLabel.setText("Equipment Type");
        backgroundPanel.add(equipmentLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 180, 30));
        backgroundPanel.add(equipmentTypeBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 550, 10));

        txtEquipmentType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEquipmentTypeActionPerformed(evt);
            }
        });
        backgroundPanel.add(txtEquipmentType, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 280, 30));

        lbEquipmentType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbEquipmentType.setForeground(new java.awt.Color(255, 255, 255));
        lbEquipmentType.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbEquipmentType.setText("Equipment Type");
        backgroundPanel.add(lbEquipmentType, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 120, 30));

        btnAdd.setBackground(new java.awt.Color(255, 255, 255));
        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ehealth/images/icons8_Insert_24px.png"))); // NOI18N
        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        backgroundPanel.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 120, 30));

        btnUpdate.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ehealth/images/icons8_Renew_24px_2.png"))); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.setEnabled(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        backgroundPanel.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 120, 120, 30));

        btnDelete.setBackground(new java.awt.Color(255, 255, 255));
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ehealth/images/icons8_Delete_Document_24px.png"))); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.setEnabled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        backgroundPanel.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 120, 120, 30));

        btnClear.setBackground(new java.awt.Color(255, 255, 255));
        btnClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ehealth/images/icons8_Reset_24px.png"))); // NOI18N
        btnClear.setText("RESET");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        backgroundPanel.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 120, 30));

        tablePanel.setBackground(backgroundPanel.getBackground());
        tablePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Equipment Types", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        tablePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        equipmentTypeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        equipmentTypeTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        equipmentTypeTable.setFocusable(false);
        equipmentTypeTable.setSelectionBackground(java.awt.Color.red);
        equipmentTypeTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        equipmentTypeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                equipmentTypeTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(equipmentTypeTable);

        tablePanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 510, 210));

        backgroundPanel.add(tablePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 530, 240));

        getContentPane().add(backgroundPanel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if(txtEquipmentType.getText().trim().isEmpty() == true) {
            JOptionPane.showMessageDialog(rootPane, "Please Fill Fields");
        }
        else {
            EquipmentTypeModel equipmentTypeModel = new EquipmentTypeModel();
            equipmentTypeModel.setEquipmentType(txtEquipmentType.getText().trim());
            equipmentTypeModel.setCreatedBy(1);
            EquipmentTypeDAO equipmentTypeDAO = new EquipmentTypeDAOImpl();
            int row = equipmentTypeDAO.addEquipmentType(equipmentTypeModel);
            if(row > 0) {
                populateMyTable();
                txtEquipmentType.setText(null);
            }
            else {
                JOptionPane.showMessageDialog(rootPane, "Record Not Added");
            }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if(txtEquipmentType.getText().trim().isEmpty() == true) {
            JOptionPane.showMessageDialog(rootPane, "Please Fill Fields");
        }else {
            EquipmentTypeModel equipmentTypeModel = new EquipmentTypeModel();
            equipmentTypeModel.setEquipmentType(txtEquipmentType.getText().trim());
            equipmentTypeModel.setModifiedBy(1);
            equipmentTypeModel.setEquipmentTypeId(equipmentTypeId);
            EquipmentTypeDAO equipmentTypeDAO = new EquipmentTypeDAOImpl();
            int row = equipmentTypeDAO.updateEquipmentType(equipmentTypeModel);
            if(row > 0) {
                populateMyTable();
                txtEquipmentType.setText(null);
            }
            else {
                JOptionPane.showMessageDialog(rootPane, "Record Not Updated");
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        EquipmentTypeModel equipmentTypeModel = new EquipmentTypeModel();
        equipmentTypeModel.setEquipmentTypeId(equipmentTypeId);
        EquipmentTypeDAO equipmentTypeDAO = new EquipmentTypeDAOImpl();
        int row = equipmentTypeDAO.deleteEquipmentType(equipmentTypeModel);
        if(row > 0) {
            populateMyTable();
            btnAdd.setEnabled(true);
            btnDelete.setEnabled(false);
            btnUpdate.setEnabled(false);
            txtEquipmentType.setText(null);
        }
        else {
            JOptionPane.showMessageDialog(rootPane, "Record Not Deleted");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtEquipmentType.setText(null);
        btnAdd.setEnabled(true);
        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);
    }//GEN-LAST:event_btnClearActionPerformed

    private void equipmentTypeTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equipmentTypeTableMouseClicked
        btnAdd.setEnabled(false);
        btnDelete.setEnabled(true);
        btnUpdate.setEnabled(true);
        equipmentTypeId = (Integer) equipmentTypeTable.getValueAt(equipmentTypeTable.getSelectedRow(), 0);
        EquipmentTypeDAO equipmentTypeDAO = new EquipmentTypeDAOImpl();
        EquipmentTypeModel equipmentTypeModel = equipmentTypeDAO.getEquipmentTypeWithId(equipmentTypeId);
        txtEquipmentType.setText(equipmentTypeModel.getEquipmentType());
    }//GEN-LAST:event_equipmentTypeTableMouseClicked

    private void txtEquipmentTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEquipmentTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEquipmentTypeActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(EquipmentTypeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(EquipmentTypeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(EquipmentTypeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(EquipmentTypeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new EquipmentTypeFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel equipmentLabel;
    private javax.swing.JSeparator equipmentTypeBar;
    private javax.swing.JTable equipmentTypeTable;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbEquipmentType;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JTextField txtEquipmentType;
    // End of variables declaration//GEN-END:variables
    public static DefaultTableModel buildTableModel(ResultSet rs) throws SQLException {
        ResultSetMetaData metaData = rs.getMetaData();
        // names of columns
        Vector<String> columnNames = new Vector<String>();
        int columnCount = metaData.getColumnCount();
        for (int column = 1; column <= columnCount; column++) {
            columnNames.add(metaData.getColumnName(column));
        }
        // data of the table
        Vector<Vector<Object>> data = new Vector<Vector<Object>>();
        while (rs.next()) {
            Vector<Object> vector = new Vector<Object>();
            for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++) {
                vector.add(rs.getObject(columnIndex));
            }
            data.add(vector);
        }
        return new DefaultTableModel(data, columnNames);
    }
    private void populateMyTable() {  
        EquipmentTypeDAO equipmentTypeDAO = new EquipmentTypeDAOImpl();
        ResultSet rs= equipmentTypeDAO.getAllEquipmentTypeResultSet();
        DefaultTableModel dtm=null;
        try {
            dtm = buildTableModel(rs);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        equipmentTypeTable.setModel(dtm);
    }
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("frameIcon.png")));
    }

    private void checkPermissions() {
        UserPermissionDAO permissionDAO = new UserPermissionDAOImpl();
        List<UserPermissionModel> permissionModels = permissionDAO.getAssignedPermissions(LoginFrame.userType);
        for (UserPermissionModel permissionModel : permissionModels) {
            if(permissionModel.getPermissionModel().getName().equals("ADD_EQUIPMENT_TYPE")) {
                btnAdd.setVisible(true);
            }
            if(permissionModel.getPermissionModel().getName().equals("UPDATE_EQUIPMENT_TYPE")) {
                btnUpdate.setVisible(true);
            }
            if(permissionModel.getPermissionModel().getName().equals("DELETE_EQUIPMENT")) {
                btnDelete.setVisible(true);
            }
        }
    }
}
