/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.e
 */
package com.ehealth.forms;

import com.ehealth.dao.Impl.UserDAOImpl;
import com.ehealth.dao.UserDAO;
import com.ehealth.models.UserModel;
import java.awt.Color;
import java.awt.Toolkit;

/**
 *
 * @author Akash
 */
public class LoginFrame extends javax.swing.JFrame {
    
    static String userType;
    static String userName;
    /**
     * Creates new form UserFrame
     */
    public LoginFrame() {
        initComponents();
        setIcon();
        setTitle("Login");
        lbCenter.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        backgroundPanel = new javax.swing.JPanel();
        upperPanel = new javax.swing.JPanel();
        lbPhoto = new javax.swing.JLabel();
        centerPanel = new javax.swing.JPanel();
        welcomeLabel = new javax.swing.JLabel();
        lowerPanel = new javax.swing.JPanel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        lbLogin = new javax.swing.JLabel();
        lbAlert = new javax.swing.JLabel();
        lbPassword = new javax.swing.JLabel();
        lbUsername = new javax.swing.JLabel();
        lbCenter = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        upperPanel.setBackground(new java.awt.Color(29, 29, 29));
        upperPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                upperPanelMouseClicked(evt);
            }
        });
        upperPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbPhoto.setBackground(new java.awt.Color(255, 255, 255));
        lbPhoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ehealth/images/Login-Icon.png"))); // NOI18N
        lbPhoto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        lbPhoto.setOpaque(true);
        upperPanel.add(lbPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 60, 160, 150));

        centerPanel.setBackground(new java.awt.Color(255, 255, 255));
        centerPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                centerPanelMouseClicked(evt);
            }
        });
        centerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        upperPanel.add(centerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 800, 500));

        welcomeLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        welcomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        welcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ehealth/images/e-health2.png"))); // NOI18N
        upperPanel.add(welcomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 370, 90));

        backgroundPanel.add(upperPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 290));

        lowerPanel.setBackground(new java.awt.Color(255, 255, 255));
        lowerPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lowerPanelMouseClicked(evt);
            }
        });
        lowerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(204, 204, 204));
        txtUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsername.setText("USERNAME");
        txtUsername.setSelectionColor(new java.awt.Color(38, 40, 55));
        txtUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUsernameMouseClicked(evt);
            }
        });
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        lowerPanel.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 400, 70));

        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(204, 204, 204));
        txtPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPassword.setText("PASSWORD");
        txtPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtPassword.setSelectionColor(new java.awt.Color(38, 40, 55));
        txtPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPasswordMouseClicked(evt);
            }
        });
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        lowerPanel.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 400, 70));

        lbLogin.setBackground(new java.awt.Color(29, 29, 29));
        lbLogin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbLogin.setForeground(new java.awt.Color(255, 255, 255));
        lbLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbLogin.setText("LOGIN");
        lbLogin.setOpaque(true);
        lbLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbLoginMouseExited(evt);
            }
        });
        lowerPanel.add(lbLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, 170, 60));

        lbAlert.setForeground(java.awt.Color.red);
        lowerPanel.add(lbAlert, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 280, 20));

        lbPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ehealth/images/password.png"))); // NOI18N
        lowerPanel.add(lbPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 60, 70));

        lbUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbUsername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ehealth/images/username.png"))); // NOI18N
        lowerPanel.add(lbUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 60, 70));

        lbCenter.setBackground(new java.awt.Color(255, 255, 255));
        lbCenter.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        lbCenter.setOpaque(true);
        lbCenter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbCenterMouseClicked(evt);
            }
        });
        lowerPanel.add(lbCenter, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, -150, 800, 500));

        jLabel1.setForeground(new java.awt.Color(38, 40, 55));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Copyright © 2018 Geeks. All rights reserved");
        lowerPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, 260, 30));

        backgroundPanel.add(lowerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 1370, 460));

        getContentPane().add(backgroundPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsernameMouseClicked
        txtUsername.setText(null);
        txtUsername.setForeground(Color.black);
        lbAlert.setText(null);
    }//GEN-LAST:event_txtUsernameMouseClicked

    private void txtPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMouseClicked
        txtPassword.setText(null);
        txtPassword.setForeground(Color.black);
        lbAlert.setText(null);
    }//GEN-LAST:event_txtPasswordMouseClicked

    private void lbLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLoginMouseClicked
        lbLogin.requestFocus();
        if((txtUsername.getText().trim().equals("USERNAME")) || (txtPassword.getText().trim().equals("PASSWORD"))
                || (txtPassword.getText().trim().isEmpty()) || (txtUsername.getText().trim().isEmpty())) {
            lbAlert.setText("*Please Enter Username and Password");
        }
        else {
            UserDAO userDAO = new UserDAOImpl();
            UserModel userModel = userDAO.getUser(txtUsername.getText().trim(), txtPassword.getText().trim());
            if(userModel!=null) {
                this.dispose();
                userType = userModel.getUserTypeModel().getUserType();            
                userName = userModel.getName();
                new MainFrame().setVisible(true);
            }
            else {
                lbAlert.setText("Please Try Again");
                txtPassword.setText(null);
                txtUsername.setText(null);
            }
        }
        
    }//GEN-LAST:event_lbLoginMouseClicked

    private void lbLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLoginMouseEntered
        lbLogin.setLocation(lbLogin.getX()+1, lbLogin.getY()+1);
    }//GEN-LAST:event_lbLoginMouseEntered

    private void lbLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLoginMouseExited
        lbLogin.setLocation(lbLogin.getX()-1, lbLogin.getY()-1);
    }//GEN-LAST:event_lbLoginMouseExited

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        txtPassword.requestFocus();
        txtPassword.setText(null);
        txtPassword.setForeground(Color.black);
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        lbLogin.requestFocus();
        if((txtUsername.getText().trim().equals("USERNAME")) || (txtUsername.getText().trim().equals("PASSWORD"))) {
            lbAlert.setText("Please Enter Valid Username and Password");
        }
        else {
            UserDAO userDAO = new UserDAOImpl();
            UserModel userModel = userDAO.getUser(txtUsername.getText().trim(), txtPassword.getText().trim());
            if(userModel!=null) {
                this.dispose();
                userType = userModel.getUserTypeModel().getUserType();            
                userName = userModel.getName();
                new MainFrame().setVisible(true);
            }
            else {
                lbAlert.setText("Please Try Again");
                txtPassword.setText(null);
                txtUsername.setText(null);
            }
        }
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void lbCenterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCenterMouseClicked
        if((txtUsername.getText().trim().isEmpty()) || (txtPassword.getText().trim().isEmpty())) {
            txtUsername.setForeground(new Color(204, 204, 204));
            txtPassword.setForeground(new Color(204, 204, 204));
            txtUsername.setText("USERNAME");
            txtPassword.setText("PASSWORD");
            lbCenter.requestFocus();
        }
    }//GEN-LAST:event_lbCenterMouseClicked

    private void centerPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_centerPanelMouseClicked
        if((txtUsername.getText().trim().isEmpty()) && (txtPassword.getText().trim().isEmpty())) {
            txtUsername.setForeground(new Color(204, 204, 204));
            txtPassword.setForeground(new Color(204, 204, 204));
            txtUsername.setText("USERNAME");
            txtPassword.setText("PASSWORD");
            lbCenter.requestFocus();
        }
    }//GEN-LAST:event_centerPanelMouseClicked

    private void upperPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upperPanelMouseClicked
        if((txtUsername.getText().trim().isEmpty()) && (txtPassword.getText().trim().isEmpty())) {
            txtUsername.setForeground(new Color(204, 204, 204));
            txtPassword.setForeground(new Color(204, 204, 204));
            txtUsername.setText("USERNAME");
            txtPassword.setText("PASSWORD");
            lbCenter.requestFocus();
        }
    }//GEN-LAST:event_upperPanelMouseClicked

    private void lowerPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lowerPanelMouseClicked
        if((txtUsername.getText().trim().isEmpty()) && (txtPassword.getText().trim().isEmpty())) {
            txtUsername.setForeground(new Color(204, 204, 204));
            txtPassword.setForeground(new Color(204, 204, 204));
            txtUsername.setText("USERNAME");
            txtPassword.setText("PASSWORD");
            lbCenter.requestFocus();
        }
    }//GEN-LAST:event_lowerPanelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbAlert;
    private javax.swing.JLabel lbCenter;
    private javax.swing.JLabel lbLogin;
    private javax.swing.JLabel lbPassword;
    private javax.swing.JLabel lbPhoto;
    private javax.swing.JLabel lbUsername;
    private javax.swing.JPanel lowerPanel;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JPanel upperPanel;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("frameIcon.png")));
    }
}
