/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ehealth.forms;

import com.ehealth.dao.Impl.UserPermissionDAOImpl;
import com.ehealth.dao.UserPermissionDAO;
import com.ehealth.models.UserPermissionModel;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.List;

/**
 *
 * @author Akash
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    
    int xx;
    int xy;
    
    
    public MainFrame() {
        initComponents();
        setIcon();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int width = (int)screenSize.getWidth();
        int height = (int)screenSize.getHeight();
        setSize(width, height);
        lbLoginUsername.setText(LoginFrame.userName);
        lbLoginRoll.setText(LoginFrame.userType);
        lbEmployee.setVisible(false);
        lbPatientBill.setVisible(false);
        lbEmployeeType.setVisible(false);
        lbAppointment.setVisible(false);
        lbBlood.setVisible(false);
        lbEquipment.setVisible(false);
        lbEquipmentType.setVisible(false);
        lbOperation.setVisible(false);
        lbOperationResult.setVisible(false);
        lbPatient.setVisible(false);
        lbRoom.setVisible(false);
        lbRoomType.setVisible(false);
        lbSpecialization.setVisible(false);
        lbShift.setVisible(false);
        lbTestPatient.setVisible(false);
        lbUserPermission.setVisible(false);
        lbUserType.setVisible(false);
        lbWard.setVisible(false);
        lbTest.setVisible(false);
        lbUser.setVisible(false);
        lbRoomAlotment.setVisible(false);
        checkPermissions();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        welcomeLabel = new javax.swing.JLabel();
        lbRoom = new javax.swing.JLabel();
        lbPatient = new javax.swing.JLabel();
        lbAppointment = new javax.swing.JLabel();
        lbEmployeeType = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbEquipmentType = new javax.swing.JLabel();
        lbEquipment = new javax.swing.JLabel();
        lbEmployee = new javax.swing.JLabel();
        lbLoginRoll = new javax.swing.JLabel();
        lbRoomType = new javax.swing.JLabel();
        lbWard = new javax.swing.JLabel();
        lbBlood = new javax.swing.JLabel();
        lbOperation = new javax.swing.JLabel();
        lbOperationResult = new javax.swing.JLabel();
        lbUserPermission = new javax.swing.JLabel();
        lbShift = new javax.swing.JLabel();
        lbSpecialization = new javax.swing.JLabel();
        lbTest = new javax.swing.JLabel();
        lbTestPatient = new javax.swing.JLabel();
        lbUserType = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbRoomAlotment = new javax.swing.JLabel();
        lbUser = new javax.swing.JLabel();
        lbPatientBill = new javax.swing.JLabel();
        lbLogout = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbLoginUsername = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("E-Health Solutions");

        backgroundPanel.setBackground(new java.awt.Color(29, 29, 29));
        backgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcomeLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        welcomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        welcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ehealth/images/e-health2.png"))); // NOI18N
        backgroundPanel.add(welcomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 380, 110));

        lbRoom.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbRoom.setForeground(new java.awt.Color(255, 255, 255));
        lbRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ehealth/images/room.png"))); // NOI18N
        lbRoom.setText("Room");
        lbRoom.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbRoom.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lbRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbRoomMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbRoomMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbRoomMouseExited(evt);
            }
        });
        backgroundPanel.add(lbRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 100, -1));

        lbPatient.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbPatient.setForeground(new java.awt.Color(255, 255, 255));
        lbPatient.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPatient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ehealth/images/patient.png"))); // NOI18N
        lbPatient.setText("Patient");
        lbPatient.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbPatient.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lbPatient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbPatientMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbPatientMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbPatientMouseExited(evt);
            }
        });
        backgroundPanel.add(lbPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 100, 130));

        lbAppointment.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbAppointment.setForeground(new java.awt.Color(255, 255, 255));
        lbAppointment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ehealth/images/appointment.png"))); // NOI18N
        lbAppointment.setText("Appointment");
        lbAppointment.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbAppointment.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lbAppointment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbAppointmentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbAppointmentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbAppointmentMouseExited(evt);
            }
        });
        backgroundPanel.add(lbAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 160, 100, -1));

        lbEmployeeType.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbEmployeeType.setForeground(new java.awt.Color(255, 255, 255));
        lbEmployeeType.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ehealth/images/employee type.png"))); // NOI18N
        lbEmployeeType.setText("Employee Type");
        lbEmployeeType.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbEmployeeType.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lbEmployeeType.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbEmployeeTypeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbEmployeeTypeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbEmployeeTypeMouseExited(evt);
            }
        });
        backgroundPanel.add(lbEmployeeType, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, 100, 130));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ehealth/images/icons8_Worker_32px.png"))); // NOI18N
        jLabel8.setText(" Roll :");
        backgroundPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 80, 30));

        lbEquipmentType.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbEquipmentType.setForeground(new java.awt.Color(255, 255, 255));
        lbEquipmentType.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ehealth/images/equipment type.png"))); // NOI18N
        lbEquipmentType.setText("Equipment Type");
        lbEquipmentType.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbEquipmentType.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lbEquipmentType.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbEquipmentTypeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbEquipmentTypeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbEquipmentTypeMouseExited(evt);
            }
        });
        backgroundPanel.add(lbEquipmentType, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 160, 100, -1));

        lbEquipment.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbEquipment.setForeground(new java.awt.Color(255, 255, 255));
        lbEquipment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ehealth/images/equipment.png"))); // NOI18N
        lbEquipment.setText("Equipment");
        lbEquipment.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbEquipment.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lbEquipment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbEquipmentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbEquipmentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbEquipmentMouseExited(evt);
            }
        });
        backgroundPanel.add(lbEquipment, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 490, 100, -1));

        lbEmployee.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbEmployee.setForeground(new java.awt.Color(255, 255, 255));
        lbEmployee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ehealth/images/employee.png"))); // NOI18N
        lbEmployee.setText("Employee");
        lbEmployee.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbEmployee.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lbEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbEmployeeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbEmployeeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbEmployeeMouseExited(evt);
            }
        });
        backgroundPanel.add(lbEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 120, 130));

        lbLoginRoll.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbLoginRoll.setForeground(new java.awt.Color(0, 174, 238));
        lbLoginRoll.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        backgroundPanel.add(lbLoginRoll, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 120, 30));

        lbRoomType.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbRoomType.setForeground(new java.awt.Color(255, 255, 255));
        lbRoomType.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ehealth/images/room type.png"))); // NOI18N
        lbRoomType.setText("Room Type");
        lbRoomType.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbRoomType.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lbRoomType.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbRoomTypeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbRoomTypeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbRoomTypeMouseExited(evt);
            }
        });
        backgroundPanel.add(lbRoomType, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 100, -1));

        lbWard.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbWard.setForeground(new java.awt.Color(255, 255, 255));
        lbWard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ehealth/images/ward.png"))); // NOI18N
        lbWard.setText("Ward");
        lbWard.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbWard.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lbWard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbWardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbWardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbWardMouseExited(evt);
            }
        });
        backgroundPanel.add(lbWard, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, 100, -1));

        lbBlood.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbBlood.setForeground(new java.awt.Color(255, 255, 255));
        lbBlood.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ehealth/images/blood.png"))); // NOI18N
        lbBlood.setText("Blood");
        lbBlood.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbBlood.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lbBlood.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBloodMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbBloodMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbBloodMouseExited(evt);
            }
        });
        backgroundPanel.add(lbBlood, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 320, 100, -1));

        lbOperation.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbOperation.setForeground(new java.awt.Color(255, 255, 255));
        lbOperation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ehealth/images/operation.png"))); // NOI18N
        lbOperation.setText("Operation");
        lbOperation.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbOperation.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lbOperation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbOperationMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbOperationMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbOperationMouseExited(evt);
            }
        });
        backgroundPanel.add(lbOperation, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 320, 100, -1));

        lbOperationResult.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbOperationResult.setForeground(new java.awt.Color(255, 255, 255));
        lbOperationResult.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ehealth/images/operation result.png"))); // NOI18N
        lbOperationResult.setText("Operation Result");
        lbOperationResult.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbOperationResult.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lbOperationResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbOperationResultMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbOperationResultMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbOperationResultMouseExited(evt);
            }
        });
        backgroundPanel.add(lbOperationResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 490, 110, -1));

        lbUserPermission.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbUserPermission.setForeground(new java.awt.Color(255, 255, 255));
        lbUserPermission.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ehealth/images/user permission.png"))); // NOI18N
        lbUserPermission.setText("User Permission");
        lbUserPermission.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbUserPermission.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lbUserPermission.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbUserPermissionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbUserPermissionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbUserPermissionMouseExited(evt);
            }
        });
        backgroundPanel.add(lbUserPermission, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 100, -1));

        lbShift.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbShift.setForeground(new java.awt.Color(255, 255, 255));
        lbShift.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ehealth/images/shift.png"))); // NOI18N
        lbShift.setText("Rotation");
        lbShift.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbShift.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lbShift.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbShiftMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbShiftMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbShiftMouseExited(evt);
            }
        });
        backgroundPanel.add(lbShift, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, 100, -1));

        lbSpecialization.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbSpecialization.setForeground(new java.awt.Color(255, 255, 255));
        lbSpecialization.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ehealth/images/specialization.png"))); // NOI18N
        lbSpecialization.setText("Specialization");
        lbSpecialization.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbSpecialization.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lbSpecialization.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbSpecializationMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbSpecializationMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbSpecializationMouseExited(evt);
            }
        });
        backgroundPanel.add(lbSpecialization, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 320, 100, -1));

        lbTest.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbTest.setForeground(new java.awt.Color(255, 255, 255));
        lbTest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ehealth/images/test.png"))); // NOI18N
        lbTest.setText("Test");
        lbTest.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbTest.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lbTest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbTestMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbTestMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbTestMouseExited(evt);
            }
        });
        backgroundPanel.add(lbTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 490, 100, -1));

        lbTestPatient.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbTestPatient.setForeground(new java.awt.Color(255, 255, 255));
        lbTestPatient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ehealth/images/test patient.png"))); // NOI18N
        lbTestPatient.setText("Test Patient");
        lbTestPatient.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbTestPatient.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lbTestPatient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbTestPatientMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbTestPatientMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbTestPatientMouseExited(evt);
            }
        });
        backgroundPanel.add(lbTestPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 490, 100, -1));

        lbUserType.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbUserType.setForeground(new java.awt.Color(255, 255, 255));
        lbUserType.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ehealth/images/User type.png"))); // NOI18N
        lbUserType.setText("User Type");
        lbUserType.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbUserType.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lbUserType.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbUserTypeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbUserTypeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbUserTypeMouseExited(evt);
            }
        });
        backgroundPanel.add(lbUserType, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 490, 100, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Copyright © 2018 Geeks. All rights reserved");
        backgroundPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 670, 240, 30));

        lbRoomAlotment.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbRoomAlotment.setForeground(new java.awt.Color(255, 255, 255));
        lbRoomAlotment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ehealth/images/room alotment.png"))); // NOI18N
        lbRoomAlotment.setText("Room Alotment");
        lbRoomAlotment.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbRoomAlotment.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lbRoomAlotment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbRoomAlotmentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbRoomAlotmentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbRoomAlotmentMouseExited(evt);
            }
        });
        backgroundPanel.add(lbRoomAlotment, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 320, 100, -1));

        lbUser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbUser.setForeground(new java.awt.Color(255, 255, 255));
        lbUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ehealth/images/system user.png"))); // NOI18N
        lbUser.setText("User");
        lbUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbUser.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lbUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbUserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbUserMouseExited(evt);
            }
        });
        backgroundPanel.add(lbUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 100, -1));

        lbPatientBill.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbPatientBill.setForeground(new java.awt.Color(255, 255, 255));
        lbPatientBill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ehealth/images/patient bill.png"))); // NOI18N
        lbPatientBill.setText("Patient Bill");
        lbPatientBill.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbPatientBill.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lbPatientBill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbPatientBillMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbPatientBillMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbPatientBillMouseExited(evt);
            }
        });
        backgroundPanel.add(lbPatientBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 160, 100, -1));

        lbLogout.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbLogout.setForeground(new java.awt.Color(255, 255, 255));
        lbLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ehealth/images/icons8_Exit_32px.png"))); // NOI18N
        lbLogout.setText("Logout");
        lbLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbLogout.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lbLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbLogoutMouseExited(evt);
            }
        });
        backgroundPanel.add(lbLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 20, 100, 60));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ehealth/images/icons8_Male_User_32px.png"))); // NOI18N
        jLabel11.setText("User :");
        backgroundPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 80, -1));

        lbLoginUsername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbLoginUsername.setForeground(new java.awt.Color(0, 174, 238));
        lbLoginUsername.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        backgroundPanel.add(lbLoginUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 120, 30));

        getContentPane().add(backgroundPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbRoomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbRoomMouseClicked
        new RoomFrame().setVisible(true);
    }//GEN-LAST:event_lbRoomMouseClicked

    private void lbPatientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPatientMouseClicked
        new PatientFrame().setVisible(true);
    }//GEN-LAST:event_lbPatientMouseClicked

    private void lbAppointmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbAppointmentMouseClicked
        new AppointmentFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbAppointmentMouseClicked

    private void lbEmployeeTypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbEmployeeTypeMouseClicked
        new EmployeeTypeFrame().setVisible(true);
    }//GEN-LAST:event_lbEmployeeTypeMouseClicked

    private void lbEquipmentTypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbEquipmentTypeMouseClicked
        new EquipmentTypeFrame().setVisible(true);
    }//GEN-LAST:event_lbEquipmentTypeMouseClicked

    private void lbEquipmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbEquipmentMouseClicked
        new EquipmentFrame().setVisible(true);
    }//GEN-LAST:event_lbEquipmentMouseClicked

    private void lbEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbEmployeeMouseClicked
        new EmployeeFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbEmployeeMouseClicked

    private void lbRoomTypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbRoomTypeMouseClicked
        new RoomTypeFrame().setVisible(true);
    }//GEN-LAST:event_lbRoomTypeMouseClicked

    private void lbWardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbWardMouseClicked
        new WardFrame().setVisible(true);
    }//GEN-LAST:event_lbWardMouseClicked

    private void lbBloodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBloodMouseClicked
        new BloodGroupFrame().setVisible(true);
    }//GEN-LAST:event_lbBloodMouseClicked

    private void lbOperationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbOperationMouseClicked
        new OperationFrame().setVisible(true);
    }//GEN-LAST:event_lbOperationMouseClicked

    private void lbOperationResultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbOperationResultMouseClicked
        new OperationResultFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbOperationResultMouseClicked

    private void lbUserPermissionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbUserPermissionMouseClicked
        new UserPermissionFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbUserPermissionMouseClicked

    private void lbShiftMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbShiftMouseClicked
        new ShiftFrame().setVisible(true);
    }//GEN-LAST:event_lbShiftMouseClicked

    private void lbSpecializationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSpecializationMouseClicked
        new SpecializationFrame().setVisible(true);
    }//GEN-LAST:event_lbSpecializationMouseClicked

    private void lbTestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbTestMouseClicked
        new TestFrame().setVisible(true);
    }//GEN-LAST:event_lbTestMouseClicked

    private void lbTestPatientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbTestPatientMouseClicked
        new TestPatientFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbTestPatientMouseClicked

    private void lbUserTypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbUserTypeMouseClicked
        new UserTypeFrame().setVisible(true);
    }//GEN-LAST:event_lbUserTypeMouseClicked

    private void lbEmployeeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbEmployeeMouseEntered
        lbEmployee.setLocation(lbEmployee.getX()+1, lbEmployee.getY()+1);
    }//GEN-LAST:event_lbEmployeeMouseEntered

    private void lbEmployeeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbEmployeeMouseExited
        lbEmployee.setLocation(lbEmployee.getX()-1, lbEmployee.getY()-1);
    }//GEN-LAST:event_lbEmployeeMouseExited

    private void lbPatientMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPatientMouseEntered
        lbPatient.setLocation(lbPatient.getX()+1, lbPatient.getY()+1);
    }//GEN-LAST:event_lbPatientMouseEntered

    private void lbPatientMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPatientMouseExited
        lbPatient.setLocation(lbPatient.getX()-1, lbPatient.getY()-1);
    }//GEN-LAST:event_lbPatientMouseExited

    private void lbAppointmentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbAppointmentMouseEntered
        lbAppointment.setLocation(lbAppointment.getX()+1, lbAppointment.getY()+1);
    }//GEN-LAST:event_lbAppointmentMouseEntered

    private void lbAppointmentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbAppointmentMouseExited
        lbAppointment.setLocation(lbAppointment.getX()-1, lbAppointment.getY()-1);
    }//GEN-LAST:event_lbAppointmentMouseExited

    private void lbEmployeeTypeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbEmployeeTypeMouseEntered
        lbEmployeeType.setLocation(lbEmployeeType.getX()+1, lbEmployeeType.getY()+1);
    }//GEN-LAST:event_lbEmployeeTypeMouseEntered

    private void lbEmployeeTypeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbEmployeeTypeMouseExited
        lbEmployeeType.setLocation(lbEmployeeType.getX()-1, lbEmployeeType.getY()-1);
    }//GEN-LAST:event_lbEmployeeTypeMouseExited

    private void lbEquipmentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbEquipmentMouseEntered
        lbEquipment.setLocation(lbEquipment.getX()+1, lbEquipment.getY()+1);
    }//GEN-LAST:event_lbEquipmentMouseEntered

    private void lbEquipmentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbEquipmentMouseExited
        lbEquipment.setLocation(lbEquipment.getX()-1, lbEquipment.getY()-1);
    }//GEN-LAST:event_lbEquipmentMouseExited

    private void lbEquipmentTypeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbEquipmentTypeMouseEntered
        lbEquipmentType.setLocation(lbEquipmentType.getX()+1, lbEquipmentType.getY()+1);
    }//GEN-LAST:event_lbEquipmentTypeMouseEntered

    private void lbEquipmentTypeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbEquipmentTypeMouseExited
        lbEquipmentType.setLocation(lbEquipmentType.getX()-1, lbEquipmentType.getY()-1);
    }//GEN-LAST:event_lbEquipmentTypeMouseExited

    private void lbRoomAlotmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbRoomAlotmentMouseClicked
        new RoomAlotmentFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbRoomAlotmentMouseClicked

    private void lbUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbUserMouseClicked
        new UserFrame().setVisible(true);
    }//GEN-LAST:event_lbUserMouseClicked

    private void lbRoomMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbRoomMouseEntered
        lbRoom.setLocation(lbRoom.getX()+1, lbRoom.getY()+1);
    }//GEN-LAST:event_lbRoomMouseEntered

    private void lbRoomMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbRoomMouseExited
        lbRoom.setLocation(lbRoom.getX()-1, lbRoom.getY()-1);
    }//GEN-LAST:event_lbRoomMouseExited

    private void lbRoomTypeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbRoomTypeMouseEntered
        lbRoomType.setLocation(lbRoomType.getX()+1, lbRoomType.getY()+1);
    }//GEN-LAST:event_lbRoomTypeMouseEntered

    private void lbRoomTypeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbRoomTypeMouseExited
        lbRoomType.setLocation(lbRoomType.getX()-1, lbRoomType.getY()-1);
    }//GEN-LAST:event_lbRoomTypeMouseExited

    private void lbWardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbWardMouseEntered
        lbWard.setLocation(lbWard.getX()+1, lbWard.getY()+1);
    }//GEN-LAST:event_lbWardMouseEntered

    private void lbWardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbWardMouseExited
        lbWard.setLocation(lbWard.getX()-1, lbWard.getY()-1);
    }//GEN-LAST:event_lbWardMouseExited

    private void lbRoomAlotmentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbRoomAlotmentMouseEntered
        lbRoomAlotment.setLocation(lbRoomAlotment.getX()+1, lbRoomAlotment.getY()+1);
    }//GEN-LAST:event_lbRoomAlotmentMouseEntered

    private void lbRoomAlotmentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbRoomAlotmentMouseExited
       lbRoomAlotment.setLocation(lbRoomAlotment.getX()-1, lbRoomAlotment.getY()-1);
    }//GEN-LAST:event_lbRoomAlotmentMouseExited

    private void lbBloodMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBloodMouseEntered
        lbBlood.setLocation(lbBlood.getX()+1, lbBlood.getY()+1);
    }//GEN-LAST:event_lbBloodMouseEntered

    private void lbBloodMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBloodMouseExited
        lbBlood.setLocation(lbBlood.getX()-1, lbBlood.getY()-1);
    }//GEN-LAST:event_lbBloodMouseExited

    private void lbOperationMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbOperationMouseEntered
        lbOperation.setLocation(lbOperation.getX()+1, lbOperation.getY()+1);
    }//GEN-LAST:event_lbOperationMouseEntered

    private void lbOperationMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbOperationMouseExited
        lbOperation.setLocation(lbOperation.getX()-1, lbOperation.getY()-1);
    }//GEN-LAST:event_lbOperationMouseExited

    private void lbOperationResultMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbOperationResultMouseEntered
        lbOperationResult.setLocation(lbOperationResult.getX()+1, lbOperationResult.getY()+1);
    }//GEN-LAST:event_lbOperationResultMouseEntered

    private void lbOperationResultMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbOperationResultMouseExited
        lbOperationResult.setLocation(lbOperationResult.getX()-1, lbOperationResult.getY()-1);
    }//GEN-LAST:event_lbOperationResultMouseExited

    private void lbUserPermissionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbUserPermissionMouseEntered
        lbUserPermission.setLocation(lbUserPermission.getX()+1, lbUserPermission.getY()+1);
    }//GEN-LAST:event_lbUserPermissionMouseEntered

    private void lbUserPermissionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbUserPermissionMouseExited
        lbUserPermission.setLocation(lbUserPermission.getX()-1, lbUserPermission.getY()-1);
    }//GEN-LAST:event_lbUserPermissionMouseExited

    private void lbShiftMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbShiftMouseEntered
        lbShift.setLocation(lbShift.getX()+1, lbShift.getY()+1);
    }//GEN-LAST:event_lbShiftMouseEntered

    private void lbShiftMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbShiftMouseExited
        lbShift.setLocation(lbShift.getX()-1, lbShift.getY()-1);
    }//GEN-LAST:event_lbShiftMouseExited

    private void lbSpecializationMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSpecializationMouseEntered
        lbSpecialization.setLocation(lbSpecialization.getX()+1, lbSpecialization.getY()+1);
    }//GEN-LAST:event_lbSpecializationMouseEntered

    private void lbSpecializationMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSpecializationMouseExited
        lbSpecialization.setLocation(lbSpecialization.getX()-1, lbSpecialization.getY()-1);
    }//GEN-LAST:event_lbSpecializationMouseExited

    private void lbTestMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbTestMouseEntered
        lbTest.setLocation(lbTest.getX()+1, lbTest.getY()+1);
    }//GEN-LAST:event_lbTestMouseEntered

    private void lbTestMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbTestMouseExited
        lbTest.setLocation(lbTest.getX()-1, lbTest.getY()-1);
    }//GEN-LAST:event_lbTestMouseExited

    private void lbTestPatientMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbTestPatientMouseEntered
        lbTestPatient.setLocation(lbTestPatient.getX()+1, lbTestPatient.getY()+1);
    }//GEN-LAST:event_lbTestPatientMouseEntered

    private void lbTestPatientMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbTestPatientMouseExited
        lbTestPatient.setLocation(lbTestPatient.getX()-1, lbTestPatient.getY()-1);
    }//GEN-LAST:event_lbTestPatientMouseExited

    private void lbUserTypeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbUserTypeMouseEntered
        lbUserType.setLocation(lbUserType.getX()+1, lbUserType.getY()+1);
    }//GEN-LAST:event_lbUserTypeMouseEntered

    private void lbUserTypeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbUserTypeMouseExited
        lbUserType.setLocation(lbUserType.getX()-1, lbUserType.getY()-1);
    }//GEN-LAST:event_lbUserTypeMouseExited

    private void lbUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbUserMouseEntered
        lbUser.setLocation(lbUser.getX()+1, lbUser.getY()+1);
    }//GEN-LAST:event_lbUserMouseEntered

    private void lbUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbUserMouseExited
        lbUser.setLocation(lbUser.getX()-1, lbUser.getY()-1);
    }//GEN-LAST:event_lbUserMouseExited

    private void lbPatientBillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPatientBillMouseClicked
        new BillFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbPatientBillMouseClicked

    private void lbPatientBillMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPatientBillMouseEntered
        lbPatientBill.setLocation(lbPatientBill.getX()+1, lbPatientBill.getY()+1);
    }//GEN-LAST:event_lbPatientBillMouseEntered

    private void lbPatientBillMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPatientBillMouseExited
        lbPatientBill.setLocation(lbPatientBill.getX()-1, lbPatientBill.getY()-1);
    }//GEN-LAST:event_lbPatientBillMouseExited

    private void lbLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLogoutMouseClicked
        new LoginFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbLogoutMouseClicked

    private void lbLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLogoutMouseEntered
        lbLogout.setLocation(lbLogout.getX()+1,lbLogout.getY());
    }//GEN-LAST:event_lbLogoutMouseEntered

    private void lbLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLogoutMouseExited
        lbLogout.setLocation(lbLogout.getX()-1,lbLogout.getY());
    }//GEN-LAST:event_lbLogoutMouseExited
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lbAppointment;
    private javax.swing.JLabel lbBlood;
    private javax.swing.JLabel lbEmployee;
    private javax.swing.JLabel lbEmployeeType;
    private javax.swing.JLabel lbEquipment;
    private javax.swing.JLabel lbEquipmentType;
    private javax.swing.JLabel lbLoginRoll;
    private javax.swing.JLabel lbLoginUsername;
    private javax.swing.JLabel lbLogout;
    private javax.swing.JLabel lbOperation;
    private javax.swing.JLabel lbOperationResult;
    private javax.swing.JLabel lbPatient;
    private javax.swing.JLabel lbPatientBill;
    private javax.swing.JLabel lbRoom;
    private javax.swing.JLabel lbRoomAlotment;
    private javax.swing.JLabel lbRoomType;
    private javax.swing.JLabel lbShift;
    private javax.swing.JLabel lbSpecialization;
    private javax.swing.JLabel lbTest;
    private javax.swing.JLabel lbTestPatient;
    private javax.swing.JLabel lbUser;
    private javax.swing.JLabel lbUserPermission;
    private javax.swing.JLabel lbUserType;
    private javax.swing.JLabel lbWard;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables

    private void checkPermissions() {
        UserPermissionDAO permissionDAO = new UserPermissionDAOImpl();
        List<UserPermissionModel> permissionModels = permissionDAO.getAssignedPermissions(LoginFrame.userType);
        for (UserPermissionModel permissionModel : permissionModels) {
            if(permissionModel.getPermissionModel().getName().equals("VIEW_EMPLOYEE")) {
                lbEmployee.setVisible(true);
            }
            if(permissionModel.getPermissionModel().getName().equals("VIEW_EMPLOYEE_TYPE")) {
                lbEmployeeType.setVisible(true);
            }
            if(permissionModel.getPermissionModel().getName().equals("VIEW_PATIENT")) {
                lbPatient.setVisible(true);
            }
            if(permissionModel.getPermissionModel().getName().equals("VIEW_APPOINTMENT")) {
                lbAppointment.setVisible(true);
            }
            if(permissionModel.getPermissionModel().getName().equals("VIEW_EQUIPMENT")) {
                lbEquipment.setVisible(true);
            }
            if(permissionModel.getPermissionModel().getName().equals("VIEW_EQUIPMENT_TYPE")) {
                lbEquipmentType.setVisible(true);
            }
            if(permissionModel.getPermissionModel().getName().equals("VIEW_PATIENT_BILL")) {
                lbPatientBill.setVisible(true);
            }
            if(permissionModel.getPermissionModel().getName().equals("VIEW_WARD")) {
                lbWard.setVisible(true);
            }
            if(permissionModel.getPermissionModel().getName().equals("VIEW_ROOM_ALOTMENT")) {
                lbRoomAlotment.setVisible(true);
            }
            if(permissionModel.getPermissionModel().getName().equals("VIEW_BLOOD")) {
                lbBlood.setVisible(true);
            }
            if(permissionModel.getPermissionModel().getName().equals("VIEW_OPERATION")) {
                lbOperation.setVisible(true);
            }
            if(permissionModel.getPermissionModel().getName().equals("VIEW_OPERATION_RESULT")) {
                lbOperationResult.setVisible(true);
            }
            if(permissionModel.getPermissionModel().getName().equals("VIEW_ROOM")) {
                lbRoom.setVisible(true);
            }
            if(permissionModel.getPermissionModel().getName().equals("VIEW_ROOM_TYPE")) {
                lbRoomType.setVisible(true);
            }
            if(permissionModel.getPermissionModel().getName().equals("VIEW_USER_PERMISSION")) {
                lbUserPermission.setVisible(true);
            }
            if(permissionModel.getPermissionModel().getName().equals("VIEW_USER")) {
                lbUser.setVisible(true);
            }
            if(permissionModel.getPermissionModel().getName().equals("VIEW_SHIFT")) {
                lbShift.setVisible(true);
            }
            if(permissionModel.getPermissionModel().getName().equals("VIEW_SPECIALIZATION")) {
                lbSpecialization.setVisible(true);
            }
            if(permissionModel.getPermissionModel().getName().equals("VIEW_TEST")) {
                lbTest.setVisible(true);
            }
            if(permissionModel.getPermissionModel().getName().equals("VIEW_TEST_PATIENT")) {
                lbTestPatient.setVisible(true);
            }
            if(permissionModel.getPermissionModel().getName().equals("VIEW_USER_TYPE")) {
                lbUserType.setVisible(true);
            }
        }
    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("frameIcon.png")));
    }
}
