/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ehealth.forms;

import com.ehealth.dao.Impl.ShiftDAOImpl;
import com.ehealth.dao.Impl.UserPermissionDAOImpl;
import com.ehealth.dao.ShiftDAO;
import com.ehealth.dao.UserPermissionDAO;
import com.ehealth.models.ShiftModel;
import com.ehealth.models.UserPermissionModel;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Akash
 */
public class ShiftFrame extends javax.swing.JFrame {

    private Integer shiftId;

    /**
     * Creates new form ShiftFrame
     */
    public ShiftFrame() {
        initComponents();
        setIcon();
        populateShiftCombo();
        populateMyTable();
        btnAdd.setVisible(false);
        btnDelete.setVisible(false);
        btnUpdate.setVisible(false);
        checkPermissions();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backGroundPanel = new javax.swing.JPanel();
        shiftLabel = new javax.swing.JLabel();
        shiftBar = new javax.swing.JSeparator();
        lbShift = new javax.swing.JLabel();
        lbTimingFrom = new javax.swing.JLabel();
        lbTimingTo = new javax.swing.JLabel();
        shiftCombo = new javax.swing.JComboBox<>();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        tablePanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        shiftTable = new javax.swing.JTable();
        timeTo = new com.github.lgooddatepicker.components.TimePicker();
        timeFrom = new com.github.lgooddatepicker.components.TimePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Shift");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backGroundPanel.setBackground(new java.awt.Color(29, 29, 29));
        backGroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        shiftLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ehealth/images/icons8_Last_6_Hours_32px.png"))); // NOI18N
        shiftLabel.setText("Shifts");
        shiftLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        shiftLabel.setForeground(new java.awt.Color(255, 255, 255));
        backGroundPanel.add(shiftLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, 30));
        backGroundPanel.add(shiftBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 550, 10));

        lbShift.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbShift.setForeground(new java.awt.Color(255, 255, 255));
        lbShift.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbShift.setText("Shift");
        backGroundPanel.add(lbShift, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 50, 30));

        lbTimingFrom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbTimingFrom.setForeground(new java.awt.Color(255, 255, 255));
        lbTimingFrom.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbTimingFrom.setText("Time");
        backGroundPanel.add(lbTimingFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 50, 30));

        lbTimingTo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbTimingTo.setForeground(new java.awt.Color(255, 255, 255));
        lbTimingTo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbTimingTo.setText("To");
        backGroundPanel.add(lbTimingTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 20, 30));

        shiftCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----Select----" }));
        backGroundPanel.add(shiftCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 260, 30));

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ehealth/images/icons8_Insert_24px.png"))); // NOI18N
        btnAdd.setText("ADD");
        btnAdd.setBackground(new java.awt.Color(255, 255, 255));
        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        backGroundPanel.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 120, 30));

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ehealth/images/icons8_Renew_24px_2.png"))); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        backGroundPanel.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 120, 30));

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ehealth/images/icons8_Delete_Document_24px.png"))); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.setBackground(new java.awt.Color(255, 255, 255));
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        backGroundPanel.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 120, 30));

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ehealth/images/icons8_Reset_24px.png"))); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.setBackground(new java.awt.Color(255, 255, 255));
        btnClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        backGroundPanel.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 120, 30));

        tablePanel.setBackground(backGroundPanel.getBackground());
        tablePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Shifts", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        tablePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        shiftTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        shiftTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                shiftTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(shiftTable);

        tablePanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 510, 240));

        backGroundPanel.add(tablePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 530, 270));

        timeTo.setBackground(backGroundPanel.getBackground());
        timeTo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backGroundPanel.add(timeTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 110, 30));

        timeFrom.setBackground(backGroundPanel.getBackground());
        timeFrom.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backGroundPanel.add(timeFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 110, 30));

        getContentPane().add(backGroundPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if((shiftCombo.getSelectedIndex()==0) || (timeFrom.getText().trim().isEmpty()) || (timeTo.getText().trim().isEmpty())) {
            JOptionPane.showMessageDialog(rootPane, "Please Fill Fields");
        }else {
            ShiftModel shiftModel = new ShiftModel();
            shiftModel.setShift(shiftCombo.getSelectedItem().toString());
            shiftModel.setTimingFrom(timeFrom.getText().trim());
            shiftModel.setTimingTo(timeTo.getText().trim());
            shiftModel.setCreatedBy(1);
            ShiftDAO shiftDAO = new ShiftDAOImpl();
            int row = shiftDAO.addShift(shiftModel);
            if(row>0) {
                populateMyTable();
                shiftCombo.setSelectedIndex(0);
                timeFrom.setText(null);
                timeTo.setText(null);
            }
            else {
                JOptionPane.showMessageDialog(rootPane, "Record Not Added");
            }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if((shiftCombo.getSelectedIndex()==0) || (timeFrom.getText().trim().isEmpty()) || (timeTo.getText().trim().isEmpty())) {
            JOptionPane.showMessageDialog(rootPane, "Please Fill Fields");
        }else {
            ShiftModel shiftModel = new ShiftModel();
            shiftModel.setShift(shiftCombo.getSelectedItem().toString());
            shiftModel.setTimingFrom(timeFrom.getText().trim());
            shiftModel.setTimingTo(timeTo.getText().trim());
            shiftModel.setModifiedBy(1);
            shiftModel.setShiftId(shiftId);
            ShiftDAO shiftDAO = new ShiftDAOImpl();
            int row = shiftDAO.updateShift(shiftModel);
            if(row>0) {
                populateMyTable();
                shiftCombo.setSelectedIndex(0);
                timeFrom.setText(null);
                timeTo.setText(null);
            }
            else {
                JOptionPane.showMessageDialog(rootPane, "Record Not Updated");
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        shiftCombo.setSelectedIndex(0);
        timeFrom.setText(null);
        timeTo.setText(null);
    }//GEN-LAST:event_btnClearActionPerformed

    private void shiftTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shiftTableMouseClicked
        shiftId = (Integer) shiftTable.getValueAt(shiftTable.getSelectedRow(), 0);
        ShiftDAO shiftDAO = new ShiftDAOImpl();
        ShiftModel shiftModel = shiftDAO.getShiftWithId(shiftId);
        shiftCombo.setSelectedItem(shiftModel.getShift());
        timeFrom.setText(shiftModel.getTimingFrom());
        timeTo.setText(shiftModel.getTimingTo());
    }//GEN-LAST:event_shiftTableMouseClicked

    /**
     * @param shiftLabeld line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ShiftFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ShiftFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ShiftFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ShiftFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ShiftFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backGroundPanel;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbShift;
    private javax.swing.JLabel lbTimingFrom;
    private javax.swing.JLabel lbTimingTo;
    private javax.swing.JSeparator shiftBar;
    private javax.swing.JComboBox<String> shiftCombo;
    private javax.swing.JLabel shiftLabel;
    private javax.swing.JTable shiftTable;
    private javax.swing.JPanel tablePanel;
    private com.github.lgooddatepicker.components.TimePicker timeFrom;
    private com.github.lgooddatepicker.components.TimePicker timeTo;
    // End of variables declaration//GEN-END:variables
    public static DefaultTableModel buildTableModel(ResultSet rs) throws SQLException {
        ResultSetMetaData metaData = rs.getMetaData();
        // names of columns
        Vector<String> columnNames = new Vector<String>();
        int columnCount = metaData.getColumnCount();
        for (int column = 1; column <= columnCount; column++) {
            columnNames.add(metaData.getColumnName(column));
        }
        // data of the table
        Vector<Vector<Object>> data = new Vector<Vector<Object>>();
        while (rs.next()) {
            Vector<Object> vector = new Vector<Object>();
            for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++) {
                vector.add(rs.getObject(columnIndex));
            }
            data.add(vector);
        }
        return new DefaultTableModel(data, columnNames);
    }
    private void populateShiftCombo() {
        ShiftDAO shiftDAO = new ShiftDAOImpl();
        List<ShiftModel> allShifts = shiftDAO.getAllShifts();
        for (ShiftModel allShift : allShifts) {
            shiftCombo.addItem(allShift.getShift());
        }
    }
    private void populateMyTable() {
       
        ShiftDAO shiftDAO= new ShiftDAOImpl();
        ResultSet rs= shiftDAO.getAllShiftResultSet();
        DefaultTableModel dtm=null;
        try {
            dtm = buildTableModel(rs);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        shiftTable.setModel(dtm);
    }
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("frameIcon.png")));
    }

    private void checkPermissions() {
        UserPermissionDAO permissionDAO = new UserPermissionDAOImpl();
        List<UserPermissionModel> permissionModels = permissionDAO.getAssignedPermissions(LoginFrame.userType);
        for (UserPermissionModel permissionModel : permissionModels) {
            if(permissionModel.getPermissionModel().getName().equals("ADD_SHIFT")) {
                btnAdd.setVisible(true);
            }
            if(permissionModel.getPermissionModel().getName().equals("UPDATE_SHIFT")) {
                btnUpdate.setVisible(true);
            }
            if(permissionModel.getPermissionModel().getName().equals("DELETE_SHIFT")) {
                btnDelete.setVisible(true);
            }
        }
    }
}
