/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ehealth.forms;

import com.ehealth.dao.AppointmentDAO;
import com.ehealth.dao.Impl.AppointmentDAOImpl;
import com.ehealth.dao.Impl.PatientDAOImpl;
import com.ehealth.dao.Impl.TestDAOImpl;
import com.ehealth.dao.Impl.TestPatientDAOImpl;
import com.ehealth.dao.Impl.UserPermissionDAOImpl;
import com.ehealth.dao.PatientDAO;
import com.ehealth.dao.TestDAO;
import com.ehealth.dao.TestPatientDAO;
import com.ehealth.dao.UserPermissionDAO;
import com.ehealth.models.AppointmentModel;
import com.ehealth.models.PatientModel;
import com.ehealth.models.TestModel;
import com.ehealth.models.TestPatientModel;
import com.ehealth.models.UserPermissionModel;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Akash
 */
public class TestPatientFrame extends javax.swing.JFrame {

    private Integer patientId;
    private Integer appointmentId;
    DefaultTableModel dtmAppointment = null;
    DefaultTableModel dtmTestPatient = null;
    private Integer testPatientId;

    /**
     * Creates new form TestPatientFrame
     */
    public TestPatientFrame() {
        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int width = (int)screenSize.getWidth();
        int height = (int)screenSize.getHeight();
        setSize(width, height);
        setTitle("Patient Test");
        setIcon();
        populateTestCombo();
        populateAppointmentTable();
        populatePatientTable();
        populateTestPatientTable();
        btnAdd.setVisible(false);
        btnDelete.setVisible(false);
        btnUpdate.setVisible(false);
        checkPermissions();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        PatientTablePanel = new javax.swing.JPanel();
        patientScroll = new javax.swing.JScrollPane();
        patientTable = new javax.swing.JTable();
        appointmentTablePanel = new javax.swing.JPanel();
        appointmentScroll = new javax.swing.JScrollPane();
        appointmentTable = new javax.swing.JTable();
        testPatientPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTestStatus = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        comboFees = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboResultDate = new com.toedter.calendar.JDateChooser();
        comboTestDate = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        comboTest = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtPatientName = new javax.swing.JTextField();
        txtTestOutcomes = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        TestTablePanel = new javax.swing.JPanel();
        testScroll = new javax.swing.JScrollPane();
        testPatientTable = new javax.swing.JTable();
        lbBack = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbLogout = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Test Patient");

        backgroundPanel.setBackground(new java.awt.Color(29, 29, 29));
        backgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PatientTablePanel.setBackground(new java.awt.Color(255, 255, 255));
        PatientTablePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Patient Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        PatientTablePanel.setOpaque(false);
        PatientTablePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        patientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        patientTable.setToolTipText("Patient Records");
        patientTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        patientTable.setFocusable(false);
        patientTable.setSelectionBackground(java.awt.Color.red);
        patientTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                patientTableMouseClicked(evt);
            }
        });
        patientScroll.setViewportView(patientTable);

        PatientTablePanel.add(patientScroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 630, 260));

        backgroundPanel.add(PatientTablePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 397, 650, 290));

        appointmentTablePanel.setBackground(new java.awt.Color(255, 255, 255));
        appointmentTablePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Appointment Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        appointmentTablePanel.setOpaque(false);
        appointmentTablePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        appointmentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        appointmentTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        appointmentTable.setFocusable(false);
        appointmentTable.setSelectionBackground(java.awt.Color.red);
        appointmentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                appointmentTableMouseClicked(evt);
            }
        });
        appointmentScroll.setViewportView(appointmentTable);

        appointmentTablePanel.add(appointmentScroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 630, 260));

        backgroundPanel.add(appointmentTablePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 397, 650, 290));

        testPatientPanel.setBackground(new java.awt.Color(255, 255, 255));
        testPatientPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Test Patient", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        testPatientPanel.setOpaque(false);
        testPatientPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Status");
        testPatientPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 90, 30));
        testPatientPanel.add(txtTestStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 170, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Patient Name");
        testPatientPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 90, 30));

        comboFees.setBackground(testPatientPanel.getBackground());
        comboFees.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "PAID", "UNPAID" }));
        testPatientPanel.add(comboFees, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 170, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Test");
        testPatientPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 90, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Test Date");
        testPatientPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 90, 30));

        comboResultDate.setBackground(backgroundPanel.getBackground());
        testPatientPanel.add(comboResultDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 170, 30));

        comboTestDate.setBackground(backgroundPanel.getBackground());
        testPatientPanel.add(comboTestDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 170, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Result Date");
        testPatientPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 90, 30));

        comboTest.setBackground(testPatientPanel.getBackground());
        comboTest.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        testPatientPanel.add(comboTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 170, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fees");
        testPatientPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 90, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Outcome");
        testPatientPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 90, 30));

        txtPatientName.setEditable(false);
        testPatientPanel.add(txtPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 170, 30));
        testPatientPanel.add(txtTestOutcomes, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 170, 30));

        btnReset.setBackground(testPatientPanel.getBackground());
        btnReset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ehealth/images/reset.png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        testPatientPanel.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 160, 50));

        btnAdd.setBackground(testPatientPanel.getBackground());
        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ehealth/images/save.png"))); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        testPatientPanel.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 160, 50));

        btnUpdate.setBackground(testPatientPanel.getBackground());
        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ehealth/images/update.png"))); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.setEnabled(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        testPatientPanel.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 160, 50));

        btnDelete.setBackground(testPatientPanel.getBackground());
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ehealth/images/delete.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setEnabled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        testPatientPanel.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 160, 50));

        backgroundPanel.add(testPatientPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 520, 310));

        TestTablePanel.setBackground(new java.awt.Color(255, 255, 255));
        TestTablePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Test Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        TestTablePanel.setForeground(new java.awt.Color(255, 255, 255));
        TestTablePanel.setOpaque(false);
        TestTablePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        testPatientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        testPatientTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        testPatientTable.setFocusable(false);
        testPatientTable.setSelectionBackground(java.awt.Color.red);
        testPatientTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                testPatientTableMouseClicked(evt);
            }
        });
        testScroll.setViewportView(testPatientTable);

        TestTablePanel.add(testScroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 760, 280));

        backgroundPanel.add(TestTablePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, 780, 310));

        lbBack.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbBack.setForeground(new java.awt.Color(255, 255, 255));
        lbBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ehealth/images/icons8_Back_48px.png"))); // NOI18N
        lbBack.setText("   Back");
        lbBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbBackMouseExited(evt);
            }
        });
        backgroundPanel.add(lbBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 60));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ehealth/images/icons8_Pulse_48px.png"))); // NOI18N
        jLabel8.setText(" Patient Test");
        backgroundPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 360, 50));

        lbLogout.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbLogout.setForeground(new java.awt.Color(255, 255, 255));
        lbLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ehealth/images/icons8_Export_48px_4.png"))); // NOI18N
        lbLogout.setText("Logout");
        lbLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbLogout.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lbLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbLogoutMouseExited(evt);
            }
        });
        backgroundPanel.add(lbLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 10, 150, 60));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Copyright © 2018 Geeks. All rights reserved");
        backgroundPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 688, 240, -1));

        getContentPane().add(backgroundPanel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void patientTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patientTableMouseClicked
        patientId = (Integer) patientTable.getValueAt(patientTable.getSelectedRow(),0);
        AppointmentDAO appointmentDAO = new AppointmentDAOImpl();
        ResultSet appointmentModels = appointmentDAO.getAllAppointmentWithPatientId(patientId);
        try {
            dtmAppointment = buildTableModel(appointmentModels);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        appointmentTable.setModel(dtmAppointment);
    }//GEN-LAST:event_patientTableMouseClicked

    private void testPatientTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_testPatientTableMouseClicked
        btnAdd.setEnabled(false);
        btnDelete.setEnabled(true);
        btnUpdate.setEnabled(true);
        testPatientId = (Integer) testPatientTable.getValueAt(testPatientTable.getSelectedRow(), 0);
        TestPatientDAO testPatientDAO = new TestPatientDAOImpl();
        TestPatientModel testPatientModel = testPatientDAO.getTesPatienttWithId(testPatientId);
        txtPatientName.setText(testPatientModel.getAppointmentModel().getPatientModel().getName());
        comboTest.setSelectedItem(testPatientModel.getTestModel().getName());
        comboTestDate.setDate(testPatientModel.getTestDate());
        comboResultDate.setDate(testPatientModel.getResultDate());
        comboFees.setSelectedItem(testPatientModel.getFees());
        txtTestOutcomes.setText(testPatientModel.getOutcome());
        txtTestStatus.setText(testPatientModel.getStatus());
    }//GEN-LAST:event_testPatientTableMouseClicked

    private void appointmentTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appointmentTableMouseClicked
        txtTestOutcomes.setText(null);
        txtTestStatus.setText(null);
        comboTest.setSelectedIndex(0);
        comboTestDate.setDate(null);
        comboResultDate.setDate(null);
        comboFees.setSelectedIndex(0);
        appointmentId = (Integer) appointmentTable.getValueAt(appointmentTable.getSelectedRow(), 0);
        String patientName = (String) appointmentTable.getValueAt(appointmentTable.getSelectedRow(), 1);
        TestPatientDAO testPatientDAO = new TestPatientDAOImpl();
        ResultSet testPatientModel = testPatientDAO.getTesPatientWithAppointmentId(appointmentId);
        try {
            dtmTestPatient = buildTableModel(testPatientModel);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        txtPatientName.setText(patientName);
        testPatientTable.setModel(dtmTestPatient);
    }//GEN-LAST:event_appointmentTableMouseClicked

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        clearFields();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if((txtPatientName.getText().trim().isEmpty()) || (comboTest.getSelectedIndex()==0) || (comboResultDate.getDate()==null) 
                || (comboResultDate.getDate()==null) || (comboFees.getSelectedIndex()==0)) {
            JOptionPane.showMessageDialog(rootPane, "Please Fill Fields");
        }else {
            TestPatientModel testPatientModel = new TestPatientModel();
            TestDAO testDAO = new TestDAOImpl();
            TestModel testModel = testDAO.getTestIdWithName(comboTest.getSelectedItem().toString());
            testPatientModel.setTestModel(testModel);
            PatientDAO patientDAO = new PatientDAOImpl();
            PatientModel patientModel = patientDAO.getPatientIdWithName(txtPatientName.getText().trim());
            AppointmentDAO appointmentDAO = new AppointmentDAOImpl();
            AppointmentModel appointmentModel = appointmentDAO.getAppointmentIdWithPatientId(patientModel.getPatientId());
            testPatientModel.setAppointmentModel(appointmentModel);
            Date date = comboTestDate.getDate();
            testPatientModel.setTestDate(new Timestamp(date.getTime()));
            date = comboResultDate.getDate();
            testPatientModel.setResultDate(new Timestamp(date.getTime()));
            testPatientModel.setFees(comboFees.getSelectedItem().toString());
            testPatientModel.setStatus(txtTestStatus.getText().trim());
            testPatientModel.setOutcome(txtTestOutcomes.getText().trim());
            testPatientModel.setCreatedBy(1);
            TestPatientDAO testPatientDAO = new TestPatientDAOImpl();
            int row = testPatientDAO.addTestPatient(testPatientModel);
            if(row > 0) {
                populateTestPatientTable();
                txtPatientName.setText(null);
                txtTestOutcomes.setText(null);
                txtTestStatus.setText(null);
                comboTest.setSelectedIndex(0);
                comboTestDate.setDate(null);
                comboResultDate.setDate(null);
                comboFees.setSelectedIndex(0);          
            }
            else {
                JOptionPane.showMessageDialog(rootPane, "Record Not Added");
            }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if((txtPatientName.getText().trim().isEmpty()) || (comboTest.getSelectedIndex()==0) || (comboResultDate.getDate()==null) 
                || (comboResultDate.getDate()==null) || (comboFees.getSelectedIndex()==0)) {
            JOptionPane.showMessageDialog(rootPane, "Please Fill Fields");
        }else {
            TestPatientModel testPatientModel = new TestPatientModel();
            TestDAO testDAO = new TestDAOImpl();
            TestModel testModel = testDAO.getTestIdWithName(comboTest.getSelectedItem().toString());
            testPatientModel.setTestModel(testModel);
            PatientDAO patientDAO = new PatientDAOImpl();
            PatientModel patientModel = patientDAO.getPatientIdWithName(txtPatientName.getText().trim());
            AppointmentDAO appointmentDAO = new AppointmentDAOImpl();
            AppointmentModel appointmentModel = appointmentDAO.getAppointmentIdWithPatientId(patientModel.getPatientId());
            testPatientModel.setAppointmentModel(appointmentModel);
            Date date = comboTestDate.getDate();
            testPatientModel.setTestDate(new Timestamp(date.getTime()));
            date = comboResultDate.getDate();
            testPatientModel.setResultDate(new Timestamp(date.getTime()));
            testPatientModel.setFees(comboFees.getSelectedItem().toString());
            testPatientModel.setStatus(txtTestStatus.getText().trim());
            testPatientModel.setOutcome(txtTestOutcomes.getText().trim());
            testPatientModel.setTestPatientId(testPatientId);
            testPatientModel.setModifiedBy(1);
            TestPatientDAO testPatientDAO = new TestPatientDAOImpl();
            int row = testPatientDAO.updateTestPatient(testPatientModel);
            if(row > 0) {
                populateTestPatientTable();
                txtPatientName.setText(null);
                txtTestOutcomes.setText(null);
                txtTestStatus.setText(null);
                comboTest.setSelectedIndex(0);
                comboTestDate.setDate(null);
                comboResultDate.setDate(null);
                comboFees.setSelectedIndex(0);
                btnUpdate.setEnabled(false);
                btnAdd.setEnabled(true);
                btnDelete.setEnabled(false);
            }
            else {
                JOptionPane.showMessageDialog(rootPane, "Record Not Updated");
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        TestPatientModel testPatientModel = new TestPatientModel();
        testPatientModel.setTestPatientId(testPatientId);
        TestPatientDAO testPatientDAO = new TestPatientDAOImpl();
        int row = testPatientDAO.deleteTestPatient(testPatientModel);
            if(row > 0) {
                populateTestPatientTable();
                txtPatientName.setText(null);
                txtTestOutcomes.setText(null);
                txtTestStatus.setText(null);
                comboTest.setSelectedIndex(0);
                comboTestDate.setDate(null);
                comboResultDate.setDate(null);
                comboFees.setSelectedIndex(0);
                btnUpdate.setEnabled(false);
                btnAdd.setEnabled(true);
                btnDelete.setEnabled(false);
            }
            else {
                JOptionPane.showMessageDialog(rootPane, "Record Not Deleted");
            }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void lbBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBackMouseClicked
        new MainFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbBackMouseClicked

    private void lbBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBackMouseEntered
        lbBack.setLocation(lbBack.getX()-1,lbBack.getY());
    }//GEN-LAST:event_lbBackMouseEntered

    private void lbBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBackMouseExited
        lbBack.setLocation(lbBack.getX()+1,lbBack.getY());
    }//GEN-LAST:event_lbBackMouseExited

    private void lbLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLogoutMouseClicked
        new LoginFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbLogoutMouseClicked

    private void lbLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLogoutMouseEntered
        lbLogout.setLocation(lbLogout.getX()+1,lbLogout.getY());
    }//GEN-LAST:event_lbLogoutMouseEntered

    private void lbLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLogoutMouseExited
        lbLogout.setLocation(lbLogout.getX()-1,lbLogout.getY());
    }//GEN-LAST:event_lbLogoutMouseExited

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TestPatientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TestPatientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TestPatientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TestPatientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TestPatientFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PatientTablePanel;
    private javax.swing.JPanel TestTablePanel;
    private javax.swing.JScrollPane appointmentScroll;
    private javax.swing.JTable appointmentTable;
    private javax.swing.JPanel appointmentTablePanel;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> comboFees;
    private com.toedter.calendar.JDateChooser comboResultDate;
    private javax.swing.JComboBox<String> comboTest;
    private com.toedter.calendar.JDateChooser comboTestDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbBack;
    private javax.swing.JLabel lbLogout;
    private javax.swing.JScrollPane patientScroll;
    private javax.swing.JTable patientTable;
    private javax.swing.JPanel testPatientPanel;
    private javax.swing.JTable testPatientTable;
    private javax.swing.JScrollPane testScroll;
    private javax.swing.JTextField txtPatientName;
    private javax.swing.JTextField txtTestOutcomes;
    private javax.swing.JTextField txtTestStatus;
    // End of variables declaration//GEN-END:variables
    public static DefaultTableModel buildTableModel(ResultSet rs) throws SQLException {
        ResultSetMetaData metaData = rs.getMetaData();
        // names of columns
        Vector<String> columnNames = new Vector<String>();
        int columnCount = metaData.getColumnCount();
        for (int column = 1; column <= columnCount; column++) {
            columnNames.add(metaData.getColumnName(column));
        }
        // data of the table
        Vector<Vector<Object>> data = new Vector<Vector<Object>>();
        while (rs.next()) {
            Vector<Object> vector = new Vector<Object>();
            for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++) {
                vector.add(rs.getObject(columnIndex));
            }
            data.add(vector);
        }
        return new DefaultTableModel(data, columnNames);
    }
    private void populateAppointmentTable() {  
        AppointmentDAO appointmentDAO = new AppointmentDAOImpl();
        ResultSet rs= appointmentDAO.getAllAppointmentsResultSet();
        //DefaultTableModel dtm=null;
        try {
            dtmAppointment = buildTableModel(rs);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        appointmentTable.setModel(dtmAppointment);
    }
    private void populatePatientTable() {  
        PatientDAO patientDAO = new PatientDAOImpl();
        ResultSet rs= patientDAO.getAllPatientResultSet();
        DefaultTableModel dtm=null;
        try {
            dtm = buildTableModel(rs);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        patientTable.setModel(dtm);
    }
    private void populateTestPatientTable() {  
        TestPatientDAO testPatientDAO = new TestPatientDAOImpl();
        ResultSet rs= testPatientDAO.getAllTestPatientResultSet();
        try {
            dtmTestPatient = buildTableModel(rs);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        testPatientTable.setModel(dtmTestPatient);
    }
    private void populateTestCombo() {
        TestDAO testDAO = new TestDAOImpl();
        List<TestModel> allTest = testDAO.getAllTests();
        for (TestModel testModel : allTest) {
            comboTest.addItem(testModel.getName());
        }
    }
    private void clearFields() {
        txtPatientName.setText(null);
        txtTestOutcomes.setText(null);
        txtTestStatus.setText(null);
        comboTest.setSelectedIndex(0);
        comboTestDate.setDate(null);
        comboResultDate.setDate(null);
        comboFees.setSelectedIndex(0);
        btnAdd.setEnabled(true);
        btnDelete.setEnabled(false);
        btnUpdate.setEnabled(false);
        populateAppointmentTable();
        populateTestPatientTable();
    }
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("frameIcon.png")));
    }

    private void checkPermissions() {
        UserPermissionDAO permissionDAO = new UserPermissionDAOImpl();
        List<UserPermissionModel> permissionModels = permissionDAO.getAssignedPermissions(LoginFrame.userType);
        for (UserPermissionModel permissionModel : permissionModels) {
            if(permissionModel.getPermissionModel().getName().equals("ADD_TEST_PATIENT")) {
                btnAdd.setVisible(true);
            }
            if(permissionModel.getPermissionModel().getName().equals("UPDATE_TEST_PATIENT")) {
                btnUpdate.setVisible(true);
            }
            if(permissionModel.getPermissionModel().getName().equals("DELETE_TEST_PATIENT")) {
                btnDelete.setVisible(true);
            }
        }
    }
    
}
