/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ehealth.forms;

import com.ehealth.dao.Impl.TestDAOImpl;
import com.ehealth.dao.Impl.UserPermissionDAOImpl;
import com.ehealth.dao.TestDAO;
import com.ehealth.dao.UserPermissionDAO;
import com.ehealth.models.TestModel;
import com.ehealth.models.UserPermissionModel;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Akash
 */
public class TestFrame extends javax.swing.JFrame {

    private Integer testId;

    /**
     * Creates new form TestFrame
     */
    public TestFrame() {
        initComponents();
        setIcon();
        populateMyTable();
        btnAdd.setVisible(false);
        btnDelete.setVisible(false);
        btnUpdate.setVisible(false);
        checkPermissions();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        shiftLabel = new javax.swing.JLabel();
        shiftBar = new javax.swing.JSeparator();
        lbRoomType = new javax.swing.JLabel();
        txtTestName = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        tablePanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        testTable = new javax.swing.JTable();
        txtTestCharges = new javax.swing.JTextField();
        lbRoomType1 = new javax.swing.JLabel();
        txtTestDuration = new javax.swing.JTextField();
        lbRoomType2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Test");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backgroundPanel.setBackground(new java.awt.Color(29, 29, 29));
        backgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        shiftLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        shiftLabel.setForeground(new java.awt.Color(255, 255, 255));
        shiftLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ehealth/images/icons8_Test_Tube_32px.png"))); // NOI18N
        shiftLabel.setText("Test Details");
        backgroundPanel.add(shiftLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 30));
        backgroundPanel.add(shiftBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 550, 10));

        lbRoomType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbRoomType.setForeground(new java.awt.Color(255, 255, 255));
        lbRoomType.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbRoomType.setText("Test");
        backgroundPanel.add(lbRoomType, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 70, 30));
        backgroundPanel.add(txtTestName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 230, 30));

        btnAdd.setBackground(new java.awt.Color(255, 255, 255));
        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ehealth/images/icons8_Insert_24px.png"))); // NOI18N
        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        backgroundPanel.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 170, 30));

        btnUpdate.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ehealth/images/icons8_Renew_24px_2.png"))); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.setEnabled(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        backgroundPanel.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 170, 30));

        btnDelete.setBackground(new java.awt.Color(255, 255, 255));
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ehealth/images/icons8_Delete_Document_24px.png"))); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.setEnabled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        backgroundPanel.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 170, 30));

        btnClear.setBackground(new java.awt.Color(255, 255, 255));
        btnClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ehealth/images/icons8_Reset_24px.png"))); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        backgroundPanel.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 170, 30));

        tablePanel.setBackground(backgroundPanel.getBackground());
        tablePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Tests", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        tablePanel.setOpaque(false);
        tablePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        testTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        testTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        testTable.setFocusable(false);
        testTable.setSelectionBackground(java.awt.Color.red);
        testTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        testTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                testTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(testTable);

        tablePanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 510, 240));

        backgroundPanel.add(tablePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 530, 270));
        backgroundPanel.add(txtTestCharges, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 230, 30));

        lbRoomType1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbRoomType1.setForeground(new java.awt.Color(255, 255, 255));
        lbRoomType1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbRoomType1.setText("Charges");
        backgroundPanel.add(lbRoomType1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 70, 30));
        backgroundPanel.add(txtTestDuration, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 230, 30));

        lbRoomType2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbRoomType2.setForeground(new java.awt.Color(255, 255, 255));
        lbRoomType2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbRoomType2.setText("Duration");
        backgroundPanel.add(lbRoomType2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 70, 30));

        getContentPane().add(backgroundPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if((txtTestName.getText().trim().isEmpty()) || (txtTestCharges.getText().trim().isEmpty()) || 
                (txtTestDuration.getText().trim().isEmpty())) {
            JOptionPane.showMessageDialog(rootPane, "Please Fill Fields");
        }
        else {
            TestModel testModel = new TestModel();
            testModel.setName(txtTestName.getText().trim());
            testModel.setCharge(Integer.parseInt(txtTestCharges.getText().trim()));
            testModel.setDuration(txtTestDuration.getText().trim());
            TestDAO testDAO = new TestDAOImpl();
            int row = testDAO.addTest(testModel);
            if(row>0) {
                populateMyTable();
                txtTestName.setText(null);
                txtTestCharges.setText(null);
                txtTestDuration.setText(null);
            }
            else {
                JOptionPane.showMessageDialog(rootPane, "Record Not Added");
            }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if((txtTestName.getText().trim().isEmpty()) || (txtTestCharges.getText().trim().isEmpty()) || 
                (txtTestDuration.getText().trim().isEmpty())) {
            JOptionPane.showMessageDialog(rootPane, "Please Fill Fields");
        }
        else {
            TestModel testModel = new TestModel();
            testModel.setName(txtTestName.getText().trim());
            testModel.setCharge(Integer.parseInt(txtTestCharges.getText().trim()));
            testModel.setDuration(txtTestDuration.getText().trim());
            testModel.setTestId(testId);
            TestDAO testDAO = new TestDAOImpl();
            int row = testDAO.updateTest(testModel);
            if(row>0) {
                populateMyTable();
                txtTestName.setText(null);
                txtTestCharges.setText(null);
                txtTestDuration.setText(null);
                btnAdd.setEnabled(true);
                btnUpdate.setEnabled(false);
                btnDelete.setEnabled(false);
            }
            else {
                JOptionPane.showMessageDialog(rootPane, "Record Not Updated");
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        Integer confirm = JOptionPane.showConfirmDialog(rootPane, "Do you realy want to delete", "Delete", JOptionPane.YES_NO_OPTION);
        if(confirm == 0) { 
            TestModel testModel = new TestModel();
            testModel.setTestId(testId);
            TestDAO testDAO = new TestDAOImpl();
            int row = testDAO.deleteTest(testModel);
            if(row>0) {
                populateMyTable();
                txtTestName.setText(null);
                txtTestCharges.setText(null);
                txtTestDuration.setText(null);
                btnAdd.setEnabled(true);
                btnUpdate.setEnabled(false);
                btnDelete.setEnabled(false);
            }
            else {
                JOptionPane.showMessageDialog(rootPane, "Record Not Deleted");
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtTestName.setText(null);
        txtTestCharges.setText(null);
        txtTestDuration.setText(null);
        btnAdd.setEnabled(true);
        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);
    }//GEN-LAST:event_btnClearActionPerformed

    private void testTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_testTableMouseClicked
        btnAdd.setEnabled(false);
        btnDelete.setEnabled(true);
        btnUpdate.setEnabled(true);
        testId = (Integer) testTable.getValueAt(testTable.getSelectedRow(), 0);
        TestDAO testDAO = new TestDAOImpl();
        TestModel testModel = testDAO.getTestWithId(testId);
        txtTestName.setText(testModel.getName());
        txtTestCharges.setText(testModel.getCharge().toString());
        txtTestDuration.setText(testModel.getDuration());
    }//GEN-LAST:event_testTableMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TestFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbRoomType;
    private javax.swing.JLabel lbRoomType1;
    private javax.swing.JLabel lbRoomType2;
    private javax.swing.JSeparator shiftBar;
    private javax.swing.JLabel shiftLabel;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JTable testTable;
    private javax.swing.JTextField txtTestCharges;
    private javax.swing.JTextField txtTestDuration;
    private javax.swing.JTextField txtTestName;
    // End of variables declaration//GEN-END:variables
    public static DefaultTableModel buildTableModel(ResultSet rs) throws SQLException {
        ResultSetMetaData metaData = rs.getMetaData();
        // names of columns
        Vector<String> columnNames = new Vector<String>();
        int columnCount = metaData.getColumnCount();
        for (int column = 1; column <= columnCount; column++) {
            columnNames.add(metaData.getColumnName(column));
        }
        // data of the table
        Vector<Vector<Object>> data = new Vector<Vector<Object>>();
        while (rs.next()) {
            Vector<Object> vector = new Vector<Object>();
            for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++) {
                vector.add(rs.getObject(columnIndex));
            }
            data.add(vector);
        }
        return new DefaultTableModel(data, columnNames);
    }
    private void populateMyTable() {
        TestDAO testDAO= new TestDAOImpl();
        ResultSet rs= testDAO.getAllTestResultSet();
        DefaultTableModel dtm=null;
        try {
            dtm = buildTableModel(rs);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        testTable.setModel(dtm);
    }
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("frameIcon.png")));
    }

    private void checkPermissions() {
        UserPermissionDAO permissionDAO = new UserPermissionDAOImpl();
        List<UserPermissionModel> permissionModels = permissionDAO.getAssignedPermissions(LoginFrame.userType);
        for (UserPermissionModel permissionModel : permissionModels) {
            if(permissionModel.getPermissionModel().getName().equals("ADD_TEST")) {
                btnAdd.setVisible(true);
            }
            if(permissionModel.getPermissionModel().getName().equals("UPDATE_TEST")) {
                btnUpdate.setVisible(true);
            }
            if(permissionModel.getPermissionModel().getName().equals("DELETE_TEST")) {
                btnDelete.setVisible(true);
            }
        }
    }
}
